// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

// 星系中可包含的天体类型（BlackHole 已移除——黑洞现为星系中心视觉元素，非独立天体）
type CelestialBody interface {
	IsCelestialBody()
}

// 所有天体共享的基础字段
type CelestialEntity interface {
	IsCelestialEntity()
	GetID() string
	GetTitle() string
	GetSlug() string
	GetExcerpt() *string
	GetCoverURL() *string
	GetGalaxy() *Galaxy
	GetPhysicsParams() *PhysicsParams
	GetCreatedAt() DateTime
	GetUpdatedAt() DateTime
}

type AddReactionInput struct {
	TargetID string `json:"targetId"`
	Emoji    string `json:"emoji"`
}

// 行星视觉美学参数
type AestheticsParams struct {
	// 星球类型（terrestrial, gas_giant, ice_giant, dwarf 等）
	PlanetType string `json:"planetType"`
	// 基础颜色 HSL
	BaseColorHsl *HSLColor `json:"baseColorHSL"`
	// 大气层颜色（HEX）
	AtmosphereColor *string `json:"atmosphereColor,omitempty"`
	// 表面粗糙度 [0, 1]
	SurfaceRoughness float64 `json:"surfaceRoughness"`
	// 是否有光环
	HasRing bool `json:"hasRing"`
	// 发光强度 [0, 1]
	GlowIntensity float64 `json:"glowIntensity"`
	// 噪声类型（perlin, simplex, voronoi, fbm）
	NoiseType string `json:"noiseType"`
}

type AestheticsParamsInput struct {
	PlanetType       string         `json:"planetType"`
	BaseColorHsl     *HSLColorInput `json:"baseColorHSL"`
	AtmosphereColor  *string        `json:"atmosphereColor,omitempty"`
	SurfaceRoughness *float64       `json:"surfaceRoughness,omitempty"`
	HasRing          *bool          `json:"hasRing,omitempty"`
	GlowIntensity    *float64       `json:"glowIntensity,omitempty"`
	NoiseType        *string        `json:"noiseType,omitempty"`
}

// 月度归档
type ArchiveMonth struct {
	Month   int       `json:"month"`
	Planets []*Planet `json:"planets"`
	Count   int       `json:"count"`
}

// 年度归档
type ArchiveResult struct {
	Year   int             `json:"year"`
	Months []*ArchiveMonth `json:"months"`
	Total  int             `json:"total"`
}

// 小行星 —— 对应草稿文章。
// 简化版行星，不含评论和关联。
type Asteroid struct {
	ID            string         `json:"id"`
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Excerpt       *string        `json:"excerpt,omitempty"`
	CoverURL      *string        `json:"coverUrl,omitempty"`
	Galaxy        *Galaxy        `json:"galaxy,omitempty"`
	PhysicsParams *PhysicsParams `json:"physicsParams,omitempty"`
	CreatedAt     DateTime       `json:"createdAt"`
	UpdatedAt     DateTime       `json:"updatedAt"`
	// Markdown 草稿内容
	Content string `json:"content"`
	// 标签
	Tags []*Tag `json:"tags"`
}

func (Asteroid) IsCelestialBody() {}

func (Asteroid) IsCelestialEntity()                    {}
func (this Asteroid) GetID() string                    { return this.ID }
func (this Asteroid) GetTitle() string                 { return this.Title }
func (this Asteroid) GetSlug() string                  { return this.Slug }
func (this Asteroid) GetExcerpt() *string              { return this.Excerpt }
func (this Asteroid) GetCoverURL() *string             { return this.CoverURL }
func (this Asteroid) GetGalaxy() *Galaxy               { return this.Galaxy }
func (this Asteroid) GetPhysicsParams() *PhysicsParams { return this.PhysicsParams }
func (this Asteroid) GetCreatedAt() DateTime           { return this.CreatedAt }
func (this Asteroid) GetUpdatedAt() DateTime           { return this.UpdatedAt }

// 认证响应
type AuthPayload struct {
	Token     string   `json:"token"`
	ExpiresAt DateTime `json:"expiresAt"`
	User      *User    `json:"user"`
}

// 三维坐标
type BaseCoordinates struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

type BaseCoordinatesInput struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

// 评论 —— 围绕天体运行的卫星。
// 支持嵌套回复和表情反应。
type Comment struct {
	ID string `json:"id"`
	// 评论所属天体的 slug
	BodySlug string `json:"bodySlug"`
	// 评论者昵称
	AuthorName string `json:"authorName"`
	// 评论者邮箱（仅管理员可见完整值）
	AuthorEmail *string `json:"authorEmail,omitempty"`
	// 评论者主页 URL
	AuthorURL *string `json:"authorUrl,omitempty"`
	// 头像种子（用于生成确定性随机头像）
	AvatarSeed string `json:"avatarSeed"`
	// 渲染后的 HTML 内容
	ContentHTML string `json:"contentHtml"`
	// 评论轨道参数（用于 3D 可视化）
	OrbitalParams *OrbitalParams `json:"orbitalParams"`
	// 父评论 ID（为 null 表示顶级评论）
	ParentID *string `json:"parentId,omitempty"`
	// 嵌套回复
	Replies []*Comment `json:"replies"`
	// 表情反应列表
	Reactions []*Reaction `json:"reactions"`
	// 是否置顶
	Pinned    bool     `json:"pinned"`
	CreatedAt DateTime `json:"createdAt"`
}

// 评论游标分页连接
type CommentConnection struct {
	Edges      []*CommentEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

// 评论游标分页边
type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type CreateCommentInput struct {
	BodySlug    string  `json:"bodySlug"`
	AuthorName  string  `json:"authorName"`
	AuthorEmail string  `json:"authorEmail"`
	AuthorURL   *string `json:"authorUrl,omitempty"`
	// Markdown 格式评论内容
	Content string `json:"content"`
	// 父评论 ID（回复时填写）
	ParentID *string `json:"parentId,omitempty"`
	// PoW 挑战 ID
	ChallengeID string `json:"challengeId"`
	// PoW 计算得到的 nonce
	PowNonce int `json:"powNonce"`
}

type CreateFriendLinkInput struct {
	Name        string  `json:"name"`
	URL         string  `json:"url"`
	Description *string `json:"description,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	Group       *string `json:"group,omitempty"`
	SortOrder   *int    `json:"sortOrder,omitempty"`
}

type CreateGalaxyInput struct {
	Name        string                  `json:"name"`
	Slug        string                  `json:"slug"`
	Description *string                 `json:"description,omitempty"`
	ParentID    *string                 `json:"parentId,omitempty"`
	Position    *BaseCoordinatesInput   `json:"position,omitempty"`
	ColorScheme *GalaxyColorSchemeInput `json:"colorScheme,omitempty"`
}

type CreatePlanetInput struct {
	Title    string  `json:"title"`
	Slug     string  `json:"slug"`
	Content  string  `json:"content"`
	Excerpt  *string `json:"excerpt,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
	GalaxyID *string `json:"galaxyId,omitempty"`
	// 所属恒星(子分类) ID
	StarID           *string                `json:"starId,omitempty"`
	TagIds           []string               `json:"tagIds,omitempty"`
	PhysicsParams    *PhysicsParamsInput    `json:"physicsParams,omitempty"`
	AestheticsParams *AestheticsParamsInput `json:"aestheticsParams,omitempty"`
	// 创建后立即发布
	Publish *bool `json:"publish,omitempty"`
}

// 友情链接
type FriendLink struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	URL         string  `json:"url"`
	Description *string `json:"description,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	// 友链分组
	Group     *string  `json:"group,omitempty"`
	SortOrder int      `json:"sortOrder"`
	CreatedAt DateTime `json:"createdAt"`
}

// 星系/恒星 —— 对应博客主分类/子分类。
// parent=null: 星系（主分类），中心有超大质量黑洞作为引力锚点和视觉标识。
// parent!=null: 恒星（子分类），围绕父星系中心黑洞公转。
// 恒星生命周期：articleCount<10 原恒星盘(暗淡) → ≥10 主序星(明亮) → ≥50 巨星 → ≥100 红巨星。
type Galaxy struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description,omitempty"`
	// 星系在宇宙中的三维位置（星系=绝对坐标，恒星=相对父星系的轨道参数）
	Position *BaseCoordinates `json:"position"`
	// 配色方案
	ColorScheme *GalaxyColorScheme `json:"colorScheme"`
	// 父级星系（null=顶级星系/主分类，非null=恒星/子分类）
	Parent *Galaxy `json:"parent,omitempty"`
	// 子恒星列表（仅主分类有子项）
	Children []*Galaxy `json:"children"`
	// 星系/恒星内所有天体
	Bodies []CelestialBody `json:"bodies"`
	// 文章总数（决定恒星生命周期阶段）
	ArticleCount int `json:"articleCount"`
	// 恒星生命周期阶段（仅子分类有效）
	StarPhase *StarPhase `json:"starPhase,omitempty"`
	CreatedAt DateTime   `json:"createdAt"`
	UpdatedAt DateTime   `json:"updatedAt"`
}

// 星系配色
type GalaxyColorScheme struct {
	Primary   string  `json:"primary"`
	Secondary string  `json:"secondary"`
	Nebula    *string `json:"nebula,omitempty"`
}

type GalaxyColorSchemeInput struct {
	Primary   string  `json:"primary"`
	Secondary string  `json:"secondary"`
	Nebula    *string `json:"nebula,omitempty"`
}

// HSL 颜色值
type HSLColor struct {
	H float64 `json:"h"`
	S float64 `json:"s"`
	L float64 `json:"l"`
}

type HSLColorInput struct {
	H float64 `json:"h"`
	S float64 `json:"s"`
	L float64 `json:"l"`
}

type Mutation struct {
}

// 评论卫星的轨道参数（用于 3D 评论环可视化）
type OrbitalParams struct {
	// 所在环索引
	RingIndex int `json:"ringIndex"`
	// 轨道半径
	OrbitRadius float64 `json:"orbitRadius"`
	// 轨道倾角（弧度）
	OrbitInclination float64 `json:"orbitInclination"`
	// 初始相位偏移（弧度）
	PhaseOffset float64 `json:"phaseOffset"`
	// 离心率
	Eccentricity float64 `json:"eccentricity"`
	// 公转速度
	OrbitalSpeed float64 `json:"orbitalSpeed"`
}

// 分页信息
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

// 天体物理轨道参数（用于宇宙场景渲染）
type PhysicsParams struct {
	// 质量（影响引力和视觉大小）
	Mass float64 `json:"mass"`
	// 轨道半径
	OrbitRadius float64 `json:"orbitRadius"`
	// 离心率 [0, 1)
	Eccentricity float64 `json:"eccentricity"`
	// 轨道倾角（弧度）
	OrbitInclination float64 `json:"orbitInclination"`
	// 初始相位偏移（弧度）
	PhaseOffset float64 `json:"phaseOffset"`
	// 公转速度
	OrbitalSpeed float64 `json:"orbitalSpeed"`
	// 纹理随机种子
	TextureSeed int `json:"textureSeed"`
}

type PhysicsParamsInput struct {
	Mass             float64  `json:"mass"`
	OrbitRadius      float64  `json:"orbitRadius"`
	Eccentricity     *float64 `json:"eccentricity,omitempty"`
	OrbitInclination *float64 `json:"orbitInclination,omitempty"`
	PhaseOffset      *float64 `json:"phaseOffset,omitempty"`
	OrbitalSpeed     *float64 `json:"orbitalSpeed,omitempty"`
	TextureSeed      *int     `json:"textureSeed,omitempty"`
}

// 行星 —— 对应已发布文章。
// 包含完整内容、评论、标签及视觉参数。
type Planet struct {
	ID            string         `json:"id"`
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Excerpt       *string        `json:"excerpt,omitempty"`
	CoverURL      *string        `json:"coverUrl,omitempty"`
	Galaxy        *Galaxy        `json:"galaxy,omitempty"`
	PhysicsParams *PhysicsParams `json:"physicsParams,omitempty"`
	CreatedAt     DateTime       `json:"createdAt"`
	UpdatedAt     DateTime       `json:"updatedAt"`
	// Markdown 正文内容（仅在单篇查询时返回）
	Content string `json:"content"`
	// 阅读时长估算（分钟）
	ReadingTime int `json:"readingTime"`
	// 是否置顶
	Pinned bool `json:"pinned"`
	// 发布时间
	PublishedAt *DateTime `json:"publishedAt,omitempty"`
	// 文章标签
	Tags []*Tag `json:"tags"`
	// 评论列表
	Comments []*Comment `json:"comments"`
	// 相关文章
	RelatedPlanets []*Planet `json:"relatedPlanets"`
	// 视觉美学参数
	AestheticsParams *AestheticsParams `json:"aestheticsParams"`
	// 浏览量
	ViewCount int `json:"viewCount"`
	// 评论数量
	CommentCount int `json:"commentCount"`
	// 所属恒星（子分类），null 表示未归类
	Star *Galaxy `json:"star,omitempty"`
}

func (Planet) IsCelestialBody() {}

func (Planet) IsCelestialEntity()                    {}
func (this Planet) GetID() string                    { return this.ID }
func (this Planet) GetTitle() string                 { return this.Title }
func (this Planet) GetSlug() string                  { return this.Slug }
func (this Planet) GetExcerpt() *string              { return this.Excerpt }
func (this Planet) GetCoverURL() *string             { return this.CoverURL }
func (this Planet) GetGalaxy() *Galaxy               { return this.Galaxy }
func (this Planet) GetPhysicsParams() *PhysicsParams { return this.PhysicsParams }
func (this Planet) GetCreatedAt() DateTime           { return this.CreatedAt }
func (this Planet) GetUpdatedAt() DateTime           { return this.UpdatedAt }

// PoW 挑战（反垃圾评论）
type PowChallenge struct {
	// 挑战 ID
	ChallengeID string `json:"challengeId"`
	// 需要找到满足条件的 nonce 的前缀
	Prefix string `json:"prefix"`
	// 要求的前导零位数
	Difficulty int `json:"difficulty"`
	// 挑战过期时间
	ExpiresAt DateTime `json:"expiresAt"`
}

// 个人主页统计
type ProfileStats struct {
	TotalPosts    int `json:"totalPosts"`
	TotalWords    int `json:"totalWords"`
	TotalComments int `json:"totalComments"`
	RunningDays   int `json:"runningDays"`
}

// 脉冲星 —— 对应博主个人简介页。
// 包含技能、时间线及社交链接等。
type Pulsar struct {
	ID            string         `json:"id"`
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Excerpt       *string        `json:"excerpt,omitempty"`
	CoverURL      *string        `json:"coverUrl,omitempty"`
	Galaxy        *Galaxy        `json:"galaxy,omitempty"`
	PhysicsParams *PhysicsParams `json:"physicsParams,omitempty"`
	CreatedAt     DateTime       `json:"createdAt"`
	UpdatedAt     DateTime       `json:"updatedAt"`
	// 个人简介（Markdown）
	Bio string `json:"bio"`
	// 技能列表
	Skills []*Skill `json:"skills"`
	// 时间线事件
	Timeline []*TimelineEvent `json:"timeline"`
	// 社交链接
	SocialLinks []*SocialLink `json:"socialLinks"`
	// 统计数据
	Stats *ProfileStats `json:"stats"`
}

func (Pulsar) IsCelestialBody() {}

func (Pulsar) IsCelestialEntity()                    {}
func (this Pulsar) GetID() string                    { return this.ID }
func (this Pulsar) GetTitle() string                 { return this.Title }
func (this Pulsar) GetSlug() string                  { return this.Slug }
func (this Pulsar) GetExcerpt() *string              { return this.Excerpt }
func (this Pulsar) GetCoverURL() *string             { return this.CoverURL }
func (this Pulsar) GetGalaxy() *Galaxy               { return this.Galaxy }
func (this Pulsar) GetPhysicsParams() *PhysicsParams { return this.PhysicsParams }
func (this Pulsar) GetCreatedAt() DateTime           { return this.CreatedAt }
func (this Pulsar) GetUpdatedAt() DateTime           { return this.UpdatedAt }

type Query struct {
}

// 表情反应
type Reaction struct {
	ID string `json:"id"`
	// 反应目标 ID（可以是评论或天体）
	TargetID string `json:"targetId"`
	// 表情符号
	Emoji string `json:"emoji"`
	// 同一表情的数量
	Count int `json:"count"`
}

// 关联度评分（用于相关文章推荐）
type RelationScore struct {
	Planet *Planet `json:"planet"`
	Score  float64 `json:"score"`
}

// 搜索结果
type SearchResult struct {
	Items    []CelestialBody `json:"items"`
	Total    int             `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"pageSize"`
	HasMore  bool            `json:"hasMore"`
}

// 站点键值配置
type SiteSetting struct {
	Key       string   `json:"key"`
	Value     JSON     `json:"value"`
	UpdatedAt DateTime `json:"updatedAt"`
}

// 站点统计
type SiteStats struct {
	TotalPlanets  int `json:"totalPlanets"`
	TotalComments int `json:"totalComments"`
	TotalGalaxies int `json:"totalGalaxies"`
	TotalTags     int `json:"totalTags"`
	TotalViews    int `json:"totalViews"`
	RunningDays   int `json:"runningDays"`
}

// 技能条目
type Skill struct {
	Name     string  `json:"name"`
	Level    int     `json:"level"`
	Category string  `json:"category"`
	Icon     *string `json:"icon,omitempty"`
}

type SkillInput struct {
	Name     string  `json:"name"`
	Level    int     `json:"level"`
	Category string  `json:"category"`
	Icon     *string `json:"icon,omitempty"`
}

// 社交链接
type SocialLink struct {
	Platform string  `json:"platform"`
	URL      string  `json:"url"`
	Icon     *string `json:"icon,omitempty"`
}

type SocialLinkInput struct {
	Platform string  `json:"platform"`
	URL      string  `json:"url"`
	Icon     *string `json:"icon,omitempty"`
}

type Subscription struct {
}

// 标签
type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	// 标签显示颜色（HEX）
	Color string `json:"color"`
	// 使用该标签的文章数量
	PostCount int `json:"postCount"`
}

// 时间线事件
type TimelineEvent struct {
	Date        DateTime `json:"date"`
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	Icon        *string  `json:"icon,omitempty"`
}

type TimelineEventInput struct {
	Date        DateTime `json:"date"`
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	Icon        *string  `json:"icon,omitempty"`
}

// 宇宙全景数据（首屏加载用）
type Universe struct {
	// 所有星系及其天体的位置坐标（不含 content）
	Galaxies []*Galaxy `json:"galaxies"`
	// 站点统计概览
	Stats *SiteStats `json:"stats"`
}

type UpdateFriendLinkInput struct {
	Name        *string `json:"name,omitempty"`
	URL         *string `json:"url,omitempty"`
	Description *string `json:"description,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	Group       *string `json:"group,omitempty"`
	SortOrder   *int    `json:"sortOrder,omitempty"`
}

type UpdateGalaxyInput struct {
	Name        *string                 `json:"name,omitempty"`
	Slug        *string                 `json:"slug,omitempty"`
	Description *string                 `json:"description,omitempty"`
	ParentID    *string                 `json:"parentId,omitempty"`
	Position    *BaseCoordinatesInput   `json:"position,omitempty"`
	ColorScheme *GalaxyColorSchemeInput `json:"colorScheme,omitempty"`
}

type UpdatePlanetInput struct {
	Title            *string                `json:"title,omitempty"`
	Content          *string                `json:"content,omitempty"`
	Excerpt          *string                `json:"excerpt,omitempty"`
	CoverURL         *string                `json:"coverUrl,omitempty"`
	GalaxyID         *string                `json:"galaxyId,omitempty"`
	TagIds           []string               `json:"tagIds,omitempty"`
	Pinned           *bool                  `json:"pinned,omitempty"`
	PhysicsParams    *PhysicsParamsInput    `json:"physicsParams,omitempty"`
	AestheticsParams *AestheticsParamsInput `json:"aestheticsParams,omitempty"`
}

type UpdateProfileInput struct {
	Title       *string               `json:"title,omitempty"`
	Bio         *string               `json:"bio,omitempty"`
	CoverURL    *string               `json:"coverUrl,omitempty"`
	Skills      []*SkillInput         `json:"skills,omitempty"`
	Timeline    []*TimelineEventInput `json:"timeline,omitempty"`
	SocialLinks []*SocialLinkInput    `json:"socialLinks,omitempty"`
}

// 上传的媒体文件
type UploadedFile struct {
	ID        string   `json:"id"`
	Filename  string   `json:"filename"`
	URL       string   `json:"url"`
	MimeType  string   `json:"mimeType"`
	Size      int      `json:"size"`
	Width     *int     `json:"width,omitempty"`
	Height    *int     `json:"height,omitempty"`
	CreatedAt DateTime `json:"createdAt"`
}

// 管理员用户
type User struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	AvatarURL   *string   `json:"avatarUrl,omitempty"`
	Role        UserRole  `json:"role"`
	LastLoginAt *DateTime `json:"lastLoginAt,omitempty"`
	CreatedAt   DateTime  `json:"createdAt"`
}

// 恒星生命周期阶段
type StarPhase string

const (
	// 原恒星盘：文章数<10，暗淡的旋转气体云团
	StarPhaseProtostar StarPhase = "PROTOSTAR"
	// 主序星：文章数≥10，明亮的自发光球体
	StarPhaseMainSequence StarPhase = "MAIN_SEQUENCE"
	// 巨星：文章数≥50，膨胀偏橙
	StarPhaseGiant StarPhase = "GIANT"
	// 红巨星：文章数≥100，深红色巨大恒星
	StarPhaseRedGiant StarPhase = "RED_GIANT"
)

var AllStarPhase = []StarPhase{
	StarPhaseProtostar,
	StarPhaseMainSequence,
	StarPhaseGiant,
	StarPhaseRedGiant,
}

func (e StarPhase) IsValid() bool {
	switch e {
	case StarPhaseProtostar, StarPhaseMainSequence, StarPhaseGiant, StarPhaseRedGiant:
		return true
	}
	return false
}

func (e StarPhase) String() string {
	return string(e)
}

func (e *StarPhase) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StarPhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StarPhase", str)
	}
	return nil
}

func (e StarPhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "ADMIN"
	UserRoleEditor UserRole = "EDITOR"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleEditor,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleEditor:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
