import type {
  GalaxyData,
  CometData,
  WormholeData,
  PulsarData,
  StarGateData,
  MeteorShowerConfig,
} from '@/hooks/useUniverseData';

/**
 * Mock universe data for development without backend.
 * 6 galaxies matching the initial galaxy plan from the concept design document,
 * with diverse stars, planets, comets, wormholes, stargates, and meteors.
 */
export const MOCK_GALAXIES: GalaxyData[] = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Galaxy 1: 杂志 (Magazine) — 精选杂志类文章
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'g1',
    name: '杂志',
    slug: 'magazine',
    description: '精选杂志类文章，涵盖科技、科学、经济、医学、文学',
    position: { x: 0, y: 0, z: 0 },
    colorScheme: { primary: '#06b6d4', secondary: '#38bdf8', nebula: '#7c3aed' },
    parent: null,
    children: [
      { id: 's1', name: '科技', slug: 'tech', articleCount: 25, starPhase: 'GIANT' },
      { id: 's2', name: '科学', slug: 'science', articleCount: 12, starPhase: 'MAIN_SEQUENCE' },
      { id: 's3', name: '经济', slug: 'economy', articleCount: 8, starPhase: 'PROTOSTAR' },
      { id: 's4', name: '医学', slug: 'medicine', articleCount: 15, starPhase: 'MAIN_SEQUENCE' },
      { id: 's5', name: '文学', slug: 'literature', articleCount: 6, starPhase: 'PROTOSTAR' },
    ],
    articleCount: 66,
    starPhase: null,
    bodies: [
      {
        id: 'p1',
        title: 'AI 大模型的涌现能力',
        slug: 'ai-emergence',
        excerpt: '探讨大语言模型的涌现行为与规模定律',
        viewCount: 5200,
        commentCount: 89,
        tags: [
          { id: 't1', name: 'AI', slug: 'ai', color: '#8b5cf6' },
          { id: 't2', name: '深度学习', slug: 'deep-learning', color: '#06b6d4' },
        ],
        physicsParams: {
          mass: 18,
          orbitRadius: 90,
          eccentricity: 0.12,
          orbitInclination: 0.08,
          phaseOffset: 0,
          orbitalSpeed: 0.35,
          textureSeed: 42,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 260, s: 70, l: 55 },
          atmosphereColor: '#8b5cf6',
          surfaceRoughness: 0.4,
          hasRing: true,
          glowIntensity: 0.5,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p2',
        title: '量子计算的现状与未来',
        slug: 'quantum-computing',
        excerpt: '从量子比特到量子纠错的前沿进展',
        viewCount: 3800,
        commentCount: 45,
        tags: [
          { id: 't3', name: '量子计算', slug: 'quantum', color: '#06b6d4' },
          { id: 't4', name: '物理', slug: 'physics', color: '#22d3ee' },
        ],
        physicsParams: {
          mass: 14,
          orbitRadius: 130,
          eccentricity: 0.2,
          orbitInclination: 0.15,
          phaseOffset: 1.8,
          orbitalSpeed: 0.28,
          textureSeed: 137,
        },
        aestheticsParams: {
          planetType: 'ice',
          baseColorHSL: { h: 190, s: 80, l: 60 },
          atmosphereColor: '#22d3ee',
          surfaceRoughness: 0.3,
          hasRing: false,
          glowIntensity: 0.4,
          noiseType: 'voronoi',
        },
      },
      {
        id: 'p3',
        title: '全球经济展望 2026',
        slug: 'global-economy-2026',
        excerpt: '主要经济体增长预测与地缘政治风险分析',
        viewCount: 2100,
        commentCount: 32,
        tags: [{ id: 't5', name: '经济', slug: 'economy', color: '#f59e0b' }],
        physicsParams: {
          mass: 7,
          orbitRadius: 65,
          eccentricity: 0.08,
          orbitInclination: 0.05,
          phaseOffset: 3.6,
          orbitalSpeed: 0.5,
          textureSeed: 256,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 40, s: 65, l: 50 },
          atmosphereColor: '#f59e0b',
          surfaceRoughness: 0.6,
          hasRing: false,
          glowIntensity: 0.25,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p4',
        title: 'mRNA 疫苗技术的新应用',
        slug: 'mrna-vaccine-applications',
        excerpt: '从新冠到癌症：mRNA 平台的治疗前景',
        viewCount: 4100,
        commentCount: 56,
        tags: [
          { id: 't6', name: '医学', slug: 'medicine', color: '#10b981' },
          { id: 't7', name: '生物技术', slug: 'biotech', color: '#34d399' },
        ],
        physicsParams: {
          mass: 10,
          orbitRadius: 105,
          eccentricity: 0.18,
          orbitInclination: 0.22,
          phaseOffset: 5.0,
          orbitalSpeed: 0.38,
          textureSeed: 512,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 155, s: 70, l: 45 },
          atmosphereColor: '#10b981',
          surfaceRoughness: 0.5,
          hasRing: false,
          glowIntensity: 0.35,
          noiseType: 'simplex',
        },
      },
    ],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Galaxy 2: 日常 (Daily) — 日常记录
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'g2',
    name: '日常',
    slug: 'daily',
    description: '日常生活记录与随想',
    position: { x: 600, y: 80, z: -200 },
    colorScheme: { primary: '#f59e0b', secondary: '#fbbf24', nebula: '#f97316' },
    parent: null,
    children: [
      { id: 's6', name: '生活', slug: 'life', articleCount: 18, starPhase: 'MAIN_SEQUENCE' },
      { id: 's7', name: '旅行', slug: 'travel', articleCount: 7, starPhase: 'PROTOSTAR' },
    ],
    articleCount: 25,
    starPhase: null,
    bodies: [
      {
        id: 'p5',
        title: '东京赏樱七日行',
        slug: 'tokyo-sakura',
        excerpt: '从上野公园到目黑川，记录一场粉色的邂逅',
        viewCount: 1800,
        commentCount: 28,
        tags: [
          { id: 't8', name: '旅行', slug: 'travel', color: '#f97316' },
          { id: 't9', name: '日本', slug: 'japan', color: '#fb923c' },
        ],
        physicsParams: {
          mass: 8,
          orbitRadius: 80,
          eccentricity: 0.1,
          orbitInclination: 0.12,
          phaseOffset: 0.5,
          orbitalSpeed: 0.42,
          textureSeed: 88,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 25, s: 75, l: 55 },
          atmosphereColor: '#fb923c',
          surfaceRoughness: 0.55,
          hasRing: false,
          glowIntensity: 0.3,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p6',
        title: '我的 Homelab 搭建记录',
        slug: 'homelab-setup',
        excerpt: 'NAS、软路由、智能家居一站式折腾指南',
        viewCount: 3200,
        commentCount: 72,
        tags: [
          { id: 't10', name: '折腾', slug: 'tinkering', color: '#eab308' },
          { id: 't11', name: '硬件', slug: 'hardware', color: '#f59e0b' },
        ],
        physicsParams: {
          mass: 12,
          orbitRadius: 120,
          eccentricity: 0.22,
          orbitInclination: 0.18,
          phaseOffset: 2.8,
          orbitalSpeed: 0.32,
          textureSeed: 333,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 45, s: 80, l: 50 },
          atmosphereColor: '#fbbf24',
          surfaceRoughness: 0.45,
          hasRing: true,
          glowIntensity: 0.45,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p7',
        title: '2026 年度阅读清单',
        slug: 'reading-list-2026',
        excerpt: '今年读了 42 本书，这是最推荐的 10 本',
        viewCount: 960,
        commentCount: 15,
        tags: [{ id: 't12', name: '阅读', slug: 'reading', color: '#a3e635' }],
        physicsParams: {
          mass: 5,
          orbitRadius: 55,
          eccentricity: 0.05,
          orbitInclination: 0.03,
          phaseOffset: 4.5,
          orbitalSpeed: 0.6,
          textureSeed: 777,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 80, s: 60, l: 50 },
          atmosphereColor: '#a3e635',
          surfaceRoughness: 0.65,
          hasRing: false,
          glowIntensity: 0.2,
          noiseType: 'voronoi',
        },
      },
    ],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Galaxy 3: 文章 (Articles) — 精选原创
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'g3',
    name: '文章',
    slug: 'articles',
    description: '深度技术原创文章',
    position: { x: -500, y: -60, z: 300 },
    colorScheme: { primary: '#3b82f6', secondary: '#60a5fa', nebula: '#6366f1' },
    parent: null,
    children: [
      { id: 's8', name: '前端', slug: 'frontend', articleCount: 35, starPhase: 'GIANT' },
      { id: 's9', name: '后端', slug: 'backend', articleCount: 28, starPhase: 'GIANT' },
      {
        id: 's10',
        name: '架构',
        slug: 'architecture',
        articleCount: 11,
        starPhase: 'MAIN_SEQUENCE',
      },
      { id: 's11', name: '安全', slug: 'security', articleCount: 9, starPhase: 'PROTOSTAR' },
    ],
    articleCount: 83,
    starPhase: null,
    bodies: [
      {
        id: 'p8',
        title: 'React 19 Server Components 深度剖析',
        slug: 'react-19-rsc',
        excerpt: '从 RSC 协议到流式渲染，全面解读 React 19 架构变革',
        viewCount: 6800,
        commentCount: 124,
        tags: [
          { id: 't13', name: 'React', slug: 'react', color: '#61dafb' },
          { id: 't14', name: 'SSR', slug: 'ssr', color: '#3b82f6' },
        ],
        physicsParams: {
          mass: 22,
          orbitRadius: 100,
          eccentricity: 0.15,
          orbitInclination: 0.1,
          phaseOffset: 0,
          orbitalSpeed: 0.3,
          textureSeed: 1001,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 200, s: 85, l: 55 },
          atmosphereColor: '#61dafb',
          surfaceRoughness: 0.35,
          hasRing: true,
          glowIntensity: 0.6,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p9',
        title: 'Go 错误处理最佳实践',
        slug: 'go-error-handling',
        excerpt: '从 errors.Is 到 slog 结构化日志的生产级错误处理方案',
        viewCount: 4200,
        commentCount: 67,
        tags: [
          { id: 't15', name: 'Go', slug: 'go', color: '#00ADD8' },
          { id: 't16', name: '最佳实践', slug: 'best-practice', color: '#2563eb' },
        ],
        physicsParams: {
          mass: 11,
          orbitRadius: 140,
          eccentricity: 0.25,
          orbitInclination: 0.2,
          phaseOffset: 2.0,
          orbitalSpeed: 0.25,
          textureSeed: 1002,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 190, s: 75, l: 50 },
          atmosphereColor: '#00ADD8',
          surfaceRoughness: 0.5,
          hasRing: false,
          glowIntensity: 0.35,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p10',
        title: 'WebGL 着色器编程完全指南',
        slug: 'webgl-shader-guide',
        excerpt: 'GLSL 从入门到自定义后处理管线',
        viewCount: 3600,
        commentCount: 48,
        tags: [
          { id: 't17', name: 'WebGL', slug: 'webgl', color: '#ef4444' },
          { id: 't18', name: 'Shader', slug: 'shader', color: '#f87171' },
        ],
        physicsParams: {
          mass: 9,
          orbitRadius: 75,
          eccentricity: 0.3,
          orbitInclination: 0.28,
          phaseOffset: 3.8,
          orbitalSpeed: 0.4,
          textureSeed: 1003,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 0, s: 70, l: 50 },
          atmosphereColor: '#ef4444',
          surfaceRoughness: 0.6,
          hasRing: false,
          glowIntensity: 0.3,
          noiseType: 'voronoi',
        },
      },
      {
        id: 'p11',
        title: 'TypeScript 类型体操实战',
        slug: 'typescript-type-gymnastics',
        excerpt: '高级泛型、条件类型与模板字面量的 30 道挑战',
        viewCount: 2900,
        commentCount: 38,
        tags: [{ id: 't19', name: 'TypeScript', slug: 'typescript', color: '#3178c6' }],
        physicsParams: {
          mass: 6,
          orbitRadius: 60,
          eccentricity: 0.08,
          orbitInclination: 0.06,
          phaseOffset: 5.2,
          orbitalSpeed: 0.55,
          textureSeed: 1004,
        },
        aestheticsParams: {
          planetType: 'ice',
          baseColorHSL: { h: 220, s: 65, l: 55 },
          atmosphereColor: '#3178c6',
          surfaceRoughness: 0.3,
          hasRing: false,
          glowIntensity: 0.25,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p12',
        title: '微服务架构的 12 个陷阱',
        slug: 'microservices-pitfalls',
        excerpt: '从分布式事务到服务发现的血泪教训',
        viewCount: 5100,
        commentCount: 95,
        tags: [
          { id: 't20', name: '架构', slug: 'architecture', color: '#6366f1' },
          { id: 't21', name: '微服务', slug: 'microservices', color: '#818cf8' },
        ],
        physicsParams: {
          mass: 16,
          orbitRadius: 155,
          eccentricity: 0.18,
          orbitInclination: 0.14,
          phaseOffset: 1.2,
          orbitalSpeed: 0.22,
          textureSeed: 1005,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 240, s: 60, l: 55 },
          atmosphereColor: '#818cf8',
          surfaceRoughness: 0.4,
          hasRing: true,
          glowIntensity: 0.5,
          noiseType: 'fbm',
        },
      },
    ],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Galaxy 4: 书籍 (Books) — 读书笔记
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'g4',
    name: '书籍',
    slug: 'books',
    description: '读书笔记与书评',
    position: { x: 400, y: -120, z: 500 },
    colorScheme: { primary: '#10b981', secondary: '#34d399', nebula: '#059669' },
    parent: null,
    children: [
      {
        id: 's12',
        name: '技术书',
        slug: 'tech-books',
        articleCount: 14,
        starPhase: 'MAIN_SEQUENCE',
      },
      { id: 's13', name: '人文社科', slug: 'humanities', articleCount: 8, starPhase: 'PROTOSTAR' },
      { id: 's14', name: '商业管理', slug: 'business', articleCount: 5, starPhase: 'PROTOSTAR' },
    ],
    articleCount: 27,
    starPhase: null,
    bodies: [
      {
        id: 'p13',
        title: '《设计数据密集型应用》读书笔记',
        slug: 'ddia-notes',
        excerpt: 'DDIA 核心章节精读：复制、分区、一致性与共识',
        viewCount: 4800,
        commentCount: 78,
        tags: [
          { id: 't22', name: '读书笔记', slug: 'book-notes', color: '#10b981' },
          { id: 't23', name: '分布式', slug: 'distributed', color: '#059669' },
        ],
        physicsParams: {
          mass: 15,
          orbitRadius: 95,
          eccentricity: 0.14,
          orbitInclination: 0.1,
          phaseOffset: 0.8,
          orbitalSpeed: 0.33,
          textureSeed: 2001,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 160, s: 70, l: 45 },
          atmosphereColor: '#34d399',
          surfaceRoughness: 0.4,
          hasRing: true,
          glowIntensity: 0.45,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p14',
        title: '《人类简史》：认知革命与虚构故事',
        slug: 'sapiens-review',
        excerpt: '为什么智人能统治地球？哈拉瑞的回答',
        viewCount: 1600,
        commentCount: 22,
        tags: [{ id: 't24', name: '人文', slug: 'humanities', color: '#a3e635' }],
        physicsParams: {
          mass: 6,
          orbitRadius: 70,
          eccentricity: 0.06,
          orbitInclination: 0.04,
          phaseOffset: 3.2,
          orbitalSpeed: 0.48,
          textureSeed: 2002,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 85, s: 55, l: 50 },
          atmosphereColor: '#a3e635',
          surfaceRoughness: 0.65,
          hasRing: false,
          glowIntensity: 0.2,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p15',
        title: '《凤凰项目》与 DevOps 转型',
        slug: 'phoenix-project',
        excerpt: '一部 IT 小说如何改变了整个行业的运维文化',
        viewCount: 2300,
        commentCount: 35,
        tags: [
          { id: 't25', name: 'DevOps', slug: 'devops', color: '#ef4444' },
          { id: 't26', name: '管理', slug: 'management', color: '#f97316' },
        ],
        physicsParams: {
          mass: 8,
          orbitRadius: 125,
          eccentricity: 0.2,
          orbitInclination: 0.16,
          phaseOffset: 5.5,
          orbitalSpeed: 0.36,
          textureSeed: 2003,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 15, s: 70, l: 50 },
          atmosphereColor: '#f97316',
          surfaceRoughness: 0.55,
          hasRing: false,
          glowIntensity: 0.3,
          noiseType: 'voronoi',
        },
      },
    ],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Galaxy 5: 论文 (Papers) — 学术论文
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'g5',
    name: '论文',
    slug: 'papers',
    description: '学术论文精选与解读',
    position: { x: -300, y: 150, z: -500 },
    colorScheme: { primary: '#d946ef', secondary: '#e879f9', nebula: '#a855f7' },
    parent: null,
    children: [
      { id: 's15', name: 'AI/ML', slug: 'ai-ml', articleCount: 20, starPhase: 'GIANT' },
      { id: 's16', name: '系统', slug: 'systems', articleCount: 10, starPhase: 'MAIN_SEQUENCE' },
    ],
    articleCount: 30,
    starPhase: null,
    bodies: [
      {
        id: 'p16',
        title: 'Attention Is All You Need 精读',
        slug: 'attention-paper',
        excerpt: 'Transformer 架构的诞生：自注意力机制如何改变了 NLP',
        viewCount: 7200,
        commentCount: 156,
        tags: [
          { id: 't27', name: 'Transformer', slug: 'transformer', color: '#d946ef' },
          { id: 't28', name: 'NLP', slug: 'nlp', color: '#e879f9' },
        ],
        physicsParams: {
          mass: 25,
          orbitRadius: 110,
          eccentricity: 0.1,
          orbitInclination: 0.08,
          phaseOffset: 0,
          orbitalSpeed: 0.2,
          textureSeed: 3001,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 290, s: 80, l: 55 },
          atmosphereColor: '#d946ef',
          surfaceRoughness: 0.3,
          hasRing: true,
          glowIntensity: 0.65,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p17',
        title: 'Raft 共识算法详解',
        slug: 'raft-consensus',
        excerpt: '比 Paxos 更易理解的分布式共识协议',
        viewCount: 3400,
        commentCount: 42,
        tags: [
          { id: 't29', name: '分布式', slug: 'distributed-sys', color: '#a855f7' },
          { id: 't30', name: '共识', slug: 'consensus', color: '#c084fc' },
        ],
        physicsParams: {
          mass: 10,
          orbitRadius: 80,
          eccentricity: 0.15,
          orbitInclination: 0.2,
          phaseOffset: 2.5,
          orbitalSpeed: 0.38,
          textureSeed: 3002,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 270, s: 60, l: 50 },
          atmosphereColor: '#a855f7',
          surfaceRoughness: 0.5,
          hasRing: false,
          glowIntensity: 0.35,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p18',
        title: 'Diffusion Models 数学推导',
        slug: 'diffusion-models-math',
        excerpt: '从 DDPM 到 Stable Diffusion 的完整数学框架',
        viewCount: 5600,
        commentCount: 88,
        tags: [
          { id: 't31', name: '生成模型', slug: 'generative', color: '#f0abfc' },
          { id: 't32', name: '数学', slug: 'math', color: '#d946ef' },
        ],
        physicsParams: {
          mass: 13,
          orbitRadius: 145,
          eccentricity: 0.22,
          orbitInclination: 0.12,
          phaseOffset: 4.8,
          orbitalSpeed: 0.26,
          textureSeed: 3003,
        },
        aestheticsParams: {
          planetType: 'ice',
          baseColorHSL: { h: 300, s: 70, l: 60 },
          atmosphereColor: '#f0abfc',
          surfaceRoughness: 0.35,
          hasRing: false,
          glowIntensity: 0.4,
          noiseType: 'voronoi',
        },
      },
    ],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Galaxy 6: 新闻 (News) — 新闻资讯
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'g6',
    name: '新闻',
    slug: 'news',
    description: '科技新闻与行业动态',
    position: { x: -600, y: 30, z: -200 },
    colorScheme: { primary: '#ef4444', secondary: '#f87171', nebula: '#dc2626' },
    parent: null,
    children: [
      { id: 's17', name: '科技新闻', slug: 'tech-news', articleCount: 45, starPhase: 'RED_GIANT' },
      {
        id: 's18',
        name: '行业分析',
        slug: 'industry',
        articleCount: 12,
        starPhase: 'MAIN_SEQUENCE',
      },
      { id: 's19', name: '开源动态', slug: 'opensource', articleCount: 8, starPhase: 'PROTOSTAR' },
    ],
    articleCount: 65,
    starPhase: null,
    bodies: [
      {
        id: 'p19',
        title: 'OpenAI 发布 GPT-5：多模态推理的新纪元',
        slug: 'gpt5-release',
        excerpt: 'GPT-5 的推理能力、多模态理解与安全对齐进展',
        viewCount: 12000,
        commentCount: 234,
        tags: [
          { id: 't33', name: 'AI', slug: 'ai-news', color: '#ef4444' },
          { id: 't34', name: 'OpenAI', slug: 'openai', color: '#f87171' },
        ],
        physicsParams: {
          mass: 28,
          orbitRadius: 85,
          eccentricity: 0.08,
          orbitInclination: 0.06,
          phaseOffset: 0.3,
          orbitalSpeed: 0.18,
          textureSeed: 4001,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 0, s: 75, l: 50 },
          atmosphereColor: '#f87171',
          surfaceRoughness: 0.3,
          hasRing: true,
          glowIntensity: 0.7,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p20',
        title: 'Rust 基金会年度报告：生态系统爆发式增长',
        slug: 'rust-foundation-report',
        excerpt: 'Rust 在 Linux 内核、WebAssembly 和嵌入式领域的扩张',
        viewCount: 3800,
        commentCount: 52,
        tags: [
          { id: 't35', name: 'Rust', slug: 'rust', color: '#fb923c' },
          { id: 't36', name: '开源', slug: 'opensource', color: '#f97316' },
        ],
        physicsParams: {
          mass: 9,
          orbitRadius: 130,
          eccentricity: 0.18,
          orbitInclination: 0.22,
          phaseOffset: 2.6,
          orbitalSpeed: 0.34,
          textureSeed: 4002,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 30, s: 80, l: 50 },
          atmosphereColor: '#fb923c',
          surfaceRoughness: 0.55,
          hasRing: false,
          glowIntensity: 0.35,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p21',
        title: 'Apple Vision Pro 2 发布：空间计算的未来',
        slug: 'vision-pro-2',
        excerpt: 'visionOS 3.0、超轻量设计与企业级应用',
        viewCount: 8500,
        commentCount: 145,
        tags: [
          { id: 't37', name: 'Apple', slug: 'apple', color: '#a3a3a3' },
          { id: 't38', name: 'XR', slug: 'xr', color: '#ef4444' },
        ],
        physicsParams: {
          mass: 20,
          orbitRadius: 160,
          eccentricity: 0.12,
          orbitInclination: 0.15,
          phaseOffset: 4.2,
          orbitalSpeed: 0.22,
          textureSeed: 4003,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 0, s: 0, l: 65 },
          atmosphereColor: '#d4d4d4',
          surfaceRoughness: 0.25,
          hasRing: true,
          glowIntensity: 0.5,
          noiseType: 'fbm',
        },
      },
    ],
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Comets — 置顶文章 (4 comets traveling across galaxies)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const MOCK_COMETS: CometData[] = [
  {
    id: 'comet-1',
    title: 'AI 大模型的涌现能力',
    slug: 'ai-emergence',
    color: '#8b5cf6',
    pathPoints: [
      { x: -400, y: 60, z: 300 },
      { x: -100, y: 20, z: 100 },
      { x: 200, y: -30, z: -100 },
      { x: 500, y: 40, z: -350 },
    ],
    speed: 0.07,
  },
  {
    id: 'comet-2',
    title: 'React 19 Server Components 深度剖析',
    slug: 'react-19-rsc',
    color: '#61dafb',
    pathPoints: [
      { x: 500, y: -20, z: 400 },
      { x: 150, y: 50, z: 150 },
      { x: -200, y: -10, z: -100 },
      { x: -550, y: 30, z: -300 },
    ],
    speed: 0.06,
  },
  {
    id: 'comet-3',
    title: 'Attention Is All You Need 精读',
    slug: 'attention-paper',
    color: '#d946ef',
    pathPoints: [
      { x: -300, y: -50, z: -400 },
      { x: 0, y: 80, z: -150 },
      { x: 300, y: -20, z: 100 },
      { x: 600, y: 50, z: 350 },
    ],
    speed: 0.05,
  },
  {
    id: 'comet-4',
    title: 'OpenAI 发布 GPT-5',
    slug: 'gpt5-release',
    color: '#ef4444',
    pathPoints: [
      { x: 600, y: 70, z: -200 },
      { x: 200, y: -40, z: 0 },
      { x: -200, y: 60, z: 200 },
      { x: -600, y: -30, z: 400 },
    ],
    speed: 0.09,
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Wormholes — 虫洞 (5 years of archives)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const MOCK_WORMHOLES: WormholeData[] = [
  { id: 'wh-2026', year: 2026, position: { x: 500, y: 10, z: -500 }, color: '#6b21a8' },
  { id: 'wh-2025', year: 2025, position: { x: 550, y: 30, z: -440 }, color: '#7c3aed' },
  { id: 'wh-2024', year: 2024, position: { x: 600, y: -10, z: -380 }, color: '#8b5cf6' },
  { id: 'wh-2023', year: 2023, position: { x: 650, y: 20, z: -320 }, color: '#a78bfa' },
  { id: 'wh-2022', year: 2022, position: { x: 700, y: -20, z: -260 }, color: '#c4b5fd' },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Pulsar — 脉冲星 (About page)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const MOCK_PULSAR: PulsarData = {
  position: { x: 0, y: 120, z: -600 },
  color: '#38bdf8',
  rotationSpeed: 3.0,
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Star Gates — 星际门 (5 friend links)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const MOCK_STARGATES: StarGateData[] = [
  {
    id: 'sg-1',
    name: 'GitHub',
    url: 'https://github.com',
    position: { x: -450, y: 40, z: -150 },
    color: '#e2e8f0',
  },
  {
    id: 'sg-2',
    name: 'V2EX',
    url: 'https://v2ex.com',
    position: { x: 350, y: -50, z: 400 },
    color: '#38bdf8',
  },
  {
    id: 'sg-3',
    name: 'Hacker News',
    url: 'https://news.ycombinator.com',
    position: { x: -150, y: 70, z: 500 },
    color: '#fb923c',
  },
  {
    id: 'sg-4',
    name: '少数派',
    url: 'https://sspai.com',
    position: { x: 500, y: -30, z: 200 },
    color: '#ef4444',
  },
  {
    id: 'sg-5',
    name: 'Lobsters',
    url: 'https://lobste.rs',
    position: { x: -500, y: -60, z: -400 },
    color: '#dc2626',
  },
  {
    id: 'sg-6',
    name: 'Reddit',
    url: 'https://reddit.com',
    position: { x: 0, y: 80, z: -550 },
    color: '#f97316',
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Meteor Shower — 流星雨 (12 simultaneous meteors)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const MOCK_METEOR_SHOWER: MeteorShowerConfig = {
  count: 12,
  spawnRadius: 800,
  color: '#38bdf8',
};
