import type { GalaxyData } from '@/hooks/useUniverseData';

/**
 * Mock universe data for development without backend.
 * Demonstrates galaxies, stars, planets with full physics/aesthetics params.
 */
export const MOCK_GALAXIES: GalaxyData[] = [
  {
    id: 'g1',
    name: 'Frontend Galaxy',
    slug: 'frontend',
    description: 'Web technologies and UI frameworks',
    position: { x: 0, y: 0, z: 0 },
    colorScheme: { primary: '#06b6d4', secondary: '#38bdf8', nebula: '#7c3aed' },
    parent: null,
    children: [
      { id: 's1', name: 'React Star', slug: 'react', articleCount: 5, starPhase: 'MAIN_SEQUENCE' },
      { id: 's2', name: 'Vue Star', slug: 'vue', articleCount: 3, starPhase: 'GIANT' },
      { id: 's3', name: 'Svelte Star', slug: 'svelte', articleCount: 2, starPhase: 'PROTOSTAR' },
    ],
    articleCount: 10,
    starPhase: null,
    bodies: [
      {
        id: 'p1',
        title: 'React 19 新特性详解',
        slug: 'react-19-features',
        excerpt: '深入探索 React 19 的 Server Components、Actions 和新 Hook',
        viewCount: 1280,
        commentCount: 24,
        tags: [
          { id: 't1', name: 'React', slug: 'react', color: '#61dafb' },
          { id: 't2', name: 'Frontend', slug: 'frontend', color: '#06b6d4' },
        ],
        physicsParams: {
          mass: 8,
          orbitRadius: 75,
          eccentricity: 0.15,
          orbitInclination: 0.1,
          phaseOffset: 0,
          orbitalSpeed: 0.4,
          textureSeed: 42,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 200, s: 70, l: 55 },
          atmosphereColor: '#61dafb',
          surfaceRoughness: 0.6,
          hasRing: false,
          glowIntensity: 0.3,
          noiseType: 'simplex',
        },
      },
      {
        id: 'p2',
        title: 'Three.js 着色器入门',
        slug: 'threejs-shaders',
        excerpt: 'GLSL 基础与自定义材质实战',
        viewCount: 890,
        commentCount: 12,
        tags: [
          { id: 't3', name: 'WebGL', slug: 'webgl', color: '#ff6b6b' },
          { id: 't4', name: '3D', slug: '3d', color: '#d946ef' },
        ],
        physicsParams: {
          mass: 12,
          orbitRadius: 130,
          eccentricity: 0.3,
          orbitInclination: 0.25,
          phaseOffset: 2.1,
          orbitalSpeed: 0.3,
          textureSeed: 137,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 30, s: 80, l: 50 },
          atmosphereColor: '#ff6b6b',
          surfaceRoughness: 0.4,
          hasRing: true,
          glowIntensity: 0.4,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p3',
        title: 'TypeScript 类型体操',
        slug: 'typescript-gymnastics',
        excerpt: '高级类型推导与条件类型技巧',
        viewCount: 2100,
        commentCount: 45,
        tags: [{ id: 't5', name: 'TypeScript', slug: 'typescript', color: '#3178c6' }],
        physicsParams: {
          mass: 5,
          orbitRadius: 60,
          eccentricity: 0.05,
          orbitInclination: 0.05,
          phaseOffset: 4.2,
          orbitalSpeed: 0.6,
          textureSeed: 256,
        },
        aestheticsParams: {
          planetType: 'ice',
          baseColorHSL: { h: 220, s: 60, l: 60 },
          atmosphereColor: '#3178c6',
          surfaceRoughness: 0.3,
          hasRing: false,
          glowIntensity: 0.2,
          noiseType: 'voronoi',
        },
      },
    ],
  },
  {
    id: 'g2',
    name: 'Backend Galaxy',
    slug: 'backend',
    description: 'Server-side technologies and infrastructure',
    position: { x: 200, y: 80, z: -150 },
    colorScheme: { primary: '#f59e0b', secondary: '#fbbf24', nebula: '#d946ef' },
    parent: null,
    children: [
      { id: 's4', name: 'Go Star', slug: 'go', articleCount: 4, starPhase: 'RED_GIANT' },
      { id: 's5', name: 'Rust Star', slug: 'rust', articleCount: 2, starPhase: 'MAIN_SEQUENCE' },
    ],
    articleCount: 6,
    starPhase: null,
    bodies: [
      {
        id: 'p4',
        title: 'Go 并发模式精讲',
        slug: 'go-concurrency',
        excerpt: 'Goroutine、Channel 与 Context 的最佳实践',
        viewCount: 3200,
        commentCount: 67,
        tags: [
          { id: 't6', name: 'Go', slug: 'go', color: '#00ADD8' },
          { id: 't7', name: 'Concurrency', slug: 'concurrency', color: '#f59e0b' },
        ],
        physicsParams: {
          mass: 15,
          orbitRadius: 110,
          eccentricity: 0.2,
          orbitInclination: 0.15,
          phaseOffset: 1.0,
          orbitalSpeed: 0.35,
          textureSeed: 88,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 45, s: 85, l: 50 },
          atmosphereColor: '#fbbf24',
          surfaceRoughness: 0.5,
          hasRing: true,
          glowIntensity: 0.5,
          noiseType: 'fbm',
        },
      },
      {
        id: 'p5',
        title: 'PostgreSQL 性能调优',
        slug: 'postgres-tuning',
        excerpt: '索引策略、查询优化与连接池配置',
        viewCount: 1500,
        commentCount: 18,
        tags: [{ id: 't8', name: 'PostgreSQL', slug: 'postgresql', color: '#336791' }],
        physicsParams: {
          mass: 6,
          orbitRadius: 70,
          eccentricity: 0.1,
          orbitInclination: 0.3,
          phaseOffset: 3.5,
          orbitalSpeed: 0.5,
          textureSeed: 333,
        },
        aestheticsParams: {
          planetType: 'terrestrial',
          baseColorHSL: { h: 210, s: 50, l: 40 },
          atmosphereColor: '#336791',
          surfaceRoughness: 0.7,
          hasRing: false,
          glowIntensity: 0.2,
          noiseType: 'simplex',
        },
      },
    ],
  },
  {
    id: 'g3',
    name: 'DevOps Galaxy',
    slug: 'devops',
    description: 'Cloud, containers, and CI/CD',
    position: { x: -180, y: -60, z: 120 },
    colorScheme: { primary: '#ef4444', secondary: '#f87171', nebula: '#06b6d4' },
    parent: null,
    children: [
      {
        id: 's6',
        name: 'Docker Star',
        slug: 'docker',
        articleCount: 3,
        starPhase: 'MAIN_SEQUENCE',
      },
    ],
    articleCount: 3,
    starPhase: null,
    bodies: [
      {
        id: 'p6',
        title: 'Kubernetes 从入门到放弃',
        slug: 'kubernetes-guide',
        excerpt: 'K8s 核心概念、部署策略与故障排查',
        viewCount: 4500,
        commentCount: 89,
        tags: [
          { id: 't9', name: 'Kubernetes', slug: 'k8s', color: '#326ce5' },
          { id: 't10', name: 'DevOps', slug: 'devops', color: '#ef4444' },
        ],
        physicsParams: {
          mass: 20,
          orbitRadius: 95,
          eccentricity: 0.25,
          orbitInclination: 0.2,
          phaseOffset: 0.5,
          orbitalSpeed: 0.25,
          textureSeed: 512,
        },
        aestheticsParams: {
          planetType: 'gas_giant',
          baseColorHSL: { h: 0, s: 70, l: 50 },
          atmosphereColor: '#f87171',
          surfaceRoughness: 0.35,
          hasRing: true,
          glowIntensity: 0.6,
          noiseType: 'fbm',
        },
      },
    ],
  },
];
