package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html"
	"time"

	"github.com/google/uuid"

	"cosmic-engine/backend/graph/generated"
	"cosmic-engine/backend/graph/model"
	"cosmic-engine/backend/internal/auth"
	"cosmic-engine/backend/internal/cache"
	"cosmic-engine/backend/internal/config"
	"cosmic-engine/backend/internal/physics"
	"cosmic-engine/backend/internal/repository"
)

// useMock returns true when no database is available (fallback to mock data).
func (r *Resolver) useMock() bool {
	return r.Repos == nil
}

// ---------- Mutations ----------

// CreatePlanet is the resolver for the createPlanet field.
func (r *mutationResolver) CreatePlanet(ctx context.Context, input model.CreatePlanetInput) (*model.Planet, error) {
	if r.useMock() {
		return mockCreatePlanet(input)
	}

	claims := GetUserClaims(ctx)
	if claims == nil {
		return nil, fmt.Errorf("UNAUTHENTICATED")
	}
	authorID, err := uuid.Parse(claims.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID in token")
	}

	body, err := r.Repos.Body.Create(ctx, input, authorID)
	if err != nil {
		return nil, fmt.Errorf("create planet: %w", err)
	}

	// Auto-calculate physics params
	// Use first 8 bytes of UUIDv7 as deterministic seed
	seed := uint64(body.ID[0])<<56 | uint64(body.ID[1])<<48 | uint64(body.ID[2])<<40 | uint64(body.ID[3])<<32 |
		uint64(body.ID[4])<<24 | uint64(body.ID[5])<<16 | uint64(body.ID[6])<<8 | uint64(body.ID[7])
	pp := physics.CalculatePlanetParams(int(body.WordCount), 0, seed)
	ppJSON, err := json.Marshal(pp)
	if err != nil {
		return nil, fmt.Errorf("marshal physics params: %w", err)
	}
	body.PhysicsParams = ppJSON

	if r.Cache != nil {
		r.Cache.InvalidateOnPlanetWrite(ctx, body.Slug)
	}

	return repository.BodyToGraphQLPlanet(body), nil
}

// UpdatePlanet is the resolver for the updatePlanet field.
func (r *mutationResolver) UpdatePlanet(ctx context.Context, slug string, input model.UpdatePlanetInput) (*model.Planet, error) {
	if r.useMock() {
		return mockUpdatePlanet(slug, input)
	}

	existing, err := r.Repos.Body.GetBySlug(ctx, slug)
	if err != nil {
		return nil, fmt.Errorf("planet not found: %s", slug)
	}

	body, err := r.Repos.Body.Update(ctx, existing.ID, input)
	if err != nil {
		return nil, fmt.Errorf("update planet: %w", err)
	}

	if r.Cache != nil {
		r.Cache.InvalidateOnPlanetWrite(ctx, slug)
	}

	return repository.BodyToGraphQLPlanet(body), nil
}

// DeletePlanet is the resolver for the deletePlanet field.
func (r *mutationResolver) DeletePlanet(ctx context.Context, slug string) (bool, error) {
	if r.useMock() {
		return true, nil
	}

	body, err := r.Repos.Body.GetBySlug(ctx, slug)
	if err != nil {
		return false, fmt.Errorf("planet not found: %s", slug)
	}

	if err := r.Repos.Body.SoftDelete(ctx, body.ID); err != nil {
		return false, fmt.Errorf("delete planet: %w", err)
	}

	if r.Cache != nil {
		r.Cache.InvalidateOnPlanetWrite(ctx, slug)
	}

	return true, nil
}

// PublishPlanet is the resolver for the publishPlanet field.
func (r *mutationResolver) PublishPlanet(ctx context.Context, slug string) (*model.Planet, error) {
	if r.useMock() {
		return mockPublishPlanet(slug)
	}

	existing, err := r.Repos.Body.GetBySlug(ctx, slug)
	if err != nil {
		return nil, fmt.Errorf("planet not found: %s", slug)
	}

	body, err := r.Repos.Body.Publish(ctx, existing.ID)
	if err != nil {
		return nil, fmt.Errorf("publish planet: %w", err)
	}

	// Increment article count on the galaxy (drives star phase lifecycle)
	_ = r.Repos.Galaxy.IncrementArticleCount(ctx, body.GalaxyID)

	if r.Cache != nil {
		r.Cache.InvalidateOnPlanetWrite(ctx, slug)
	}

	return repository.BodyToGraphQLPlanet(body), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	if r.useMock() {
		return mockCreateComment(input)
	}

	// TODO: validate PoW challenge (input.ChallengeID, input.PowNonce)

	body, err := r.Repos.Body.GetBySlug(ctx, input.BodySlug)
	if err != nil {
		return nil, fmt.Errorf("body not found: %s", input.BodySlug)
	}

	// Calculate satellite orbital params
	totalComments := int(body.CommentCount)
	seed := uint64(time.Now().UnixNano())
	orbit := physics.CalculateSatelliteOrbit(totalComments, totalComments+1, seed)
	orbitalJSON, err := json.Marshal(orbit)
	if err != nil {
		return nil, fmt.Errorf("marshal orbital params: %w", err)
	}

	comment, err := r.Repos.Comment.Create(ctx, body.ID, input, orbitalJSON)
	if err != nil {
		return nil, fmt.Errorf("create comment: %w", err)
	}

	// Increment comment count on the body
	_ = r.Repos.Body.IncrementCommentCount(ctx, body.ID)

	if r.Cache != nil {
		r.Cache.InvalidateOnCommentWrite(ctx, input.BodySlug)
	}

	result := repository.CommentToGraphQL(comment)
	result.BodySlug = input.BodySlug
	return result, nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	if r.useMock() {
		return true, nil
	}

	uid, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid comment ID")
	}

	// Look up comment to get body_id for decrementing count
	comment, err := r.Repos.Comment.GetByID(ctx, uid)
	if err != nil {
		return false, fmt.Errorf("comment not found")
	}

	if err := r.Repos.Comment.SoftDelete(ctx, uid); err != nil {
		return false, fmt.Errorf("delete comment: %w", err)
	}

	_ = r.Repos.Body.DecrementCommentCount(ctx, comment.BodyID)

	return true, nil
}

// PinComment is the resolver for the pinComment field.
func (r *mutationResolver) PinComment(ctx context.Context, id string, pinned bool) (*model.Comment, error) {
	if r.useMock() {
		return mockPinComment(id, pinned)
	}

	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid comment ID")
	}

	comment, err := r.Repos.Comment.Pin(ctx, uid, pinned)
	if err != nil {
		return nil, fmt.Errorf("pin comment: %w", err)
	}

	return repository.CommentToGraphQL(comment), nil
}

// AddReaction is the resolver for the addReaction field.
func (r *mutationResolver) AddReaction(ctx context.Context, input model.AddReactionInput) (*model.Reaction, error) {
	// Reactions stay mock for now — requires session hash infrastructure
	return &model.Reaction{
		ID:       fmt.Sprintf("r-%d", time.Now().UnixNano()),
		TargetID: input.TargetID,
		Emoji:    input.Emoji,
		Count:    1,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, totpCode *string) (*model.AuthPayload, error) {
	if r.useMock() {
		return mockLogin(r.Config, email, password)
	}

	// Real DB authentication
	user, err := r.Repos.User.GetByEmail(ctx, email)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	ok, err := auth.VerifyPassword(password, user.PasswordHash)
	if err != nil || !ok {
		return nil, fmt.Errorf("invalid credentials")
	}

	cfg := r.Config
	token, expiresAt, err := auth.GenerateToken(
		cfg.Auth.JWTSecret, user.ID.String(), user.Email, string(user.Role), cfg.Auth.JWTExpireHrs,
	)
	if err != nil {
		return nil, fmt.Errorf("generate token: %w", err)
	}

	return &model.AuthPayload{
		Token:     token,
		ExpiresAt: model.DateTime{Time: expiresAt},
		User:      repository.UserToGraphQL(user),
	}, nil
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, filename string, mimeType string, size int) (*model.UploadedFile, error) {
	// File upload is a REST concern; this mutation registers metadata only
	return &model.UploadedFile{
		ID:        fmt.Sprintf("up-%d", time.Now().UnixNano()),
		Filename:  filename,
		URL:       fmt.Sprintf("/uploads/%s", filename),
		MimeType:  mimeType,
		Size:      size,
		CreatedAt: model.DateTime{Time: time.Now()},
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.Pulsar, error) {
	p := mockPulsar
	if input.Title != nil {
		p.Title = *input.Title
	}
	if input.Bio != nil {
		p.Bio = *input.Bio
	}
	p.UpdatedAt = model.DateTime{Time: time.Now()}
	return p, nil
}

// CreateGalaxy is the resolver for the createGalaxy field.
func (r *mutationResolver) CreateGalaxy(ctx context.Context, input model.CreateGalaxyInput) (*model.Galaxy, error) {
	if r.useMock() {
		return mockCreateGalaxy(input)
	}

	g, err := r.Repos.Galaxy.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("create galaxy: %w", err)
	}

	if r.Cache != nil {
		r.Cache.InvalidateOnGalaxyWrite(ctx, g.Slug)
	}

	return repository.GalaxyToGraphQL(g), nil
}

// UpdateGalaxy is the resolver for the updateGalaxy field.
func (r *mutationResolver) UpdateGalaxy(ctx context.Context, id string, input model.UpdateGalaxyInput) (*model.Galaxy, error) {
	if r.useMock() {
		return mockUpdateGalaxy(id, input)
	}

	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid galaxy ID")
	}

	g, err := r.Repos.Galaxy.Update(ctx, uid, input)
	if err != nil {
		return nil, fmt.Errorf("update galaxy: %w", err)
	}

	if r.Cache != nil {
		r.Cache.InvalidateOnGalaxyWrite(ctx, g.Slug)
	}

	return repository.GalaxyToGraphQL(g), nil
}

// UpdateSiteSetting is the resolver for the updateSiteSetting field.
func (r *mutationResolver) UpdateSiteSetting(ctx context.Context, key string, value model.JSON) (*model.SiteSetting, error) {
	if r.useMock() {
		return &model.SiteSetting{Key: key, Value: value, UpdatedAt: model.DateTime{Time: time.Now()}}, nil
	}

	valJSON, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("marshal setting value: %w", err)
	}
	s, err := r.Repos.Settings.Upsert(ctx, key, valJSON)
	if err != nil {
		return nil, fmt.Errorf("update setting: %w", err)
	}

	return repository.SettingToGraphQL(s), nil
}

// RequestPowChallenge is the resolver for the requestPowChallenge field.
func (r *mutationResolver) RequestPowChallenge(ctx context.Context) (*model.PowChallenge, error) {
	return &model.PowChallenge{
		ChallengeID: fmt.Sprintf("pow-%d", time.Now().UnixNano()),
		Prefix:      base64.StdEncoding.EncodeToString([]byte("mock-challenge")),
		Difficulty:  4,
		ExpiresAt:   model.DateTime{Time: time.Now().Add(5 * time.Minute)},
	}, nil
}

// CreateFriendLink is the resolver for the createFriendLink field.
func (r *mutationResolver) CreateFriendLink(ctx context.Context, input model.CreateFriendLinkInput) (*model.FriendLink, error) {
	if r.useMock() {
		return mockCreateFriendLink(input)
	}

	fl, err := r.Repos.FriendLink.Create(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("create friend link: %w", err)
	}

	if r.Cache != nil {
		r.Cache.InvalidateOnFriendLinkWrite(ctx)
	}

	return repository.FriendLinkToGraphQL(fl), nil
}

// UpdateFriendLink is the resolver for the updateFriendLink field.
func (r *mutationResolver) UpdateFriendLink(ctx context.Context, id string, input model.UpdateFriendLinkInput) (*model.FriendLink, error) {
	if r.useMock() {
		return mockUpdateFriendLink(id, input)
	}
	// TODO: implement with repository
	return nil, fmt.Errorf("not implemented with database")
}

// DeleteFriendLink is the resolver for the deleteFriendLink field.
func (r *mutationResolver) DeleteFriendLink(ctx context.Context, id string) (bool, error) {
	if r.useMock() {
		return true, nil
	}

	uid, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid friend link ID")
	}

	if err := r.Repos.FriendLink.Delete(ctx, uid); err != nil {
		return false, fmt.Errorf("delete friend link: %w", err)
	}

	if r.Cache != nil {
		r.Cache.InvalidateOnFriendLinkWrite(ctx)
	}

	return true, nil
}

// ---------- Queries ----------

// Universe is the resolver for the universe field.
func (r *queryResolver) Universe(ctx context.Context) (*model.Universe, error) {
	if r.useMock() {
		stats, _ := r.Stats(ctx)
		return &model.Universe{Galaxies: mockGalaxies, Stats: stats}, nil
	}

	// Check cache
	if r.Cache != nil {
		var cached model.Universe
		if r.Cache.Get(ctx, cache.PrefixUniverse, &cached) {
			return &cached, nil
		}
	}

	dbGalaxies, err := r.Repos.Galaxy.ListGalaxies(ctx)
	if err != nil {
		return nil, fmt.Errorf("list galaxies: %w", err)
	}

	galaxies := make([]*model.Galaxy, len(dbGalaxies))
	for i, g := range dbGalaxies {
		galaxies[i] = repository.GalaxyToGraphQL(&g)
	}

	stats, _ := r.Stats(ctx)
	result := &model.Universe{Galaxies: galaxies, Stats: stats}

	if r.Cache != nil {
		r.Cache.Set(ctx, cache.PrefixUniverse, result, cache.TTLUniverse)
	}

	return result, nil
}

// Galaxy is the resolver for the galaxy field.
func (r *queryResolver) Galaxy(ctx context.Context, slug string) (*model.Galaxy, error) {
	if r.useMock() {
		for _, g := range mockGalaxies {
			if g.Slug == slug {
				return g, nil
			}
		}
		return nil, nil
	}

	if r.Cache != nil {
		var cached model.Galaxy
		if r.Cache.Get(ctx, cache.GalaxyKey(slug), &cached) {
			return &cached, nil
		}
	}

	g, err := r.Repos.Galaxy.GetBySlug(ctx, slug)
	if err != nil {
		return nil, nil
	}

	result := repository.GalaxyToGraphQL(g)

	if r.Cache != nil {
		r.Cache.Set(ctx, cache.GalaxyKey(slug), result, cache.TTLGalaxy)
	}

	return result, nil
}

// Planet is the resolver for the planet field.
func (r *queryResolver) Planet(ctx context.Context, slug string) (*model.Planet, error) {
	if r.useMock() {
		for _, p := range mockPlanets {
			if p.Slug == slug {
				return p, nil
			}
		}
		return nil, nil
	}

	if r.Cache != nil {
		var cached model.Planet
		if r.Cache.Get(ctx, cache.PlanetKey(slug), &cached) {
			return &cached, nil
		}
	}

	b, err := r.Repos.Body.GetBySlug(ctx, slug)
	if err != nil {
		return nil, nil
	}

	result := repository.BodyToGraphQLPlanet(b)

	// Populate tags
	tags, err := r.Repos.Tag.ListByBodyID(ctx, b.ID)
	if err == nil {
		for _, t := range tags {
			result.Tags = append(result.Tags, repository.TagToGraphQL(&t))
		}
	}

	if r.Cache != nil {
		r.Cache.Set(ctx, cache.PlanetKey(slug), result, cache.TTLPlanet)
	}

	return result, nil
}

// SearchBodies is the resolver for the searchBodies field.
func (r *queryResolver) SearchBodies(ctx context.Context, query string, galaxySlug *string, page *int, pageSize *int) (*model.SearchResult, error) {
	if r.useMock() {
		return mockSearchBodies()
	}

	pg := 1
	if page != nil {
		pg = *page
	}
	ps := 10
	if pageSize != nil {
		ps = *pageSize
	}
	offset := int32((pg - 1) * ps)

	bodies, total, err := r.Repos.Body.Search(ctx, query, int32(ps), offset)
	if err != nil {
		return nil, fmt.Errorf("search: %w", err)
	}

	items := make([]model.CelestialBody, len(bodies))
	for i, b := range bodies {
		items[i] = repository.BodyToGraphQLPlanet(&b)
	}

	return &model.SearchResult{
		Items:    items,
		Total:    int(total),
		Page:     pg,
		PageSize: ps,
		HasMore:  int64(pg*ps) < total,
	}, nil
}

// ArchiveByYear is the resolver for the archiveByYear field.
func (r *queryResolver) ArchiveByYear(ctx context.Context, year int) (*model.ArchiveResult, error) {
	if r.useMock() {
		return mockArchiveByYear(year)
	}

	bodies, err := r.Repos.Body.Archive(ctx, year)
	if err != nil {
		return nil, fmt.Errorf("archive: %w", err)
	}

	monthMap := make(map[int][]*model.Planet)
	for _, b := range bodies {
		if b.PublishedAt.Valid {
			m := int(b.PublishedAt.Time.Month())
			monthMap[m] = append(monthMap[m], repository.BodyToGraphQLPlanet(&b))
		}
	}

	months := make([]*model.ArchiveMonth, 0)
	total := 0
	for m := 1; m <= 12; m++ {
		if planets, ok := monthMap[m]; ok {
			months = append(months, &model.ArchiveMonth{Month: m, Planets: planets, Count: len(planets)})
			total += len(planets)
		}
	}

	return &model.ArchiveResult{Year: year, Months: months, Total: total}, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.Pulsar, error) {
	return mockPulsar, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, bodySlug string, cursor *string, limit *int) (*model.CommentConnection, error) {
	if r.useMock() {
		return mockCommentConnection(bodySlug)
	}

	lim := int32(20)
	if limit != nil {
		lim = int32(*limit)
	}
	offset := int32(0)
	if cursor != nil {
		if _, err := fmt.Sscanf(*cursor, "%d", &offset); err != nil || offset < 0 {
			offset = 0
		}
	}
	if lim < 1 {
		lim = 20
	}
	if lim > 100 {
		lim = 100
	}

	comments, total, err := r.Repos.Comment.ListByBody(ctx, bodySlug, lim, offset)
	if err != nil {
		return nil, fmt.Errorf("list comments: %w", err)
	}

	edges := make([]*model.CommentEdge, len(comments))
	for i, c := range comments {
		gc := repository.CommentToGraphQL(&c)
		gc.BodySlug = bodySlug
		edges[i] = &model.CommentEdge{
			Cursor: fmt.Sprintf("%d", offset+int32(i)),
			Node:   gc,
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	return &model.CommentConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     int64(int(offset)+len(comments)) < total,
			HasPreviousPage: offset > 0,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int(total),
	}, nil
}

// RelatedPlanets is the resolver for the relatedPlanets field.
func (r *queryResolver) RelatedPlanets(ctx context.Context, bodyID string, limit *int) ([]*model.RelationScore, error) {
	if r.useMock() {
		return mockRelatedPlanets(bodyID, limit)
	}

	// For now, return popular planets as related (semantic search not yet implemented)
	lim := 3
	if limit != nil {
		lim = *limit
	}
	bodies, err := r.Repos.Body.Popular(ctx, int32(lim+1))
	if err != nil {
		return nil, nil
	}

	var results []*model.RelationScore
	for i, b := range bodies {
		if b.ID.String() == bodyID {
			continue
		}
		results = append(results, &model.RelationScore{
			Planet: repository.BodyToGraphQLPlanet(&b),
			Score:  0.9 - float64(i)*0.1,
		})
		if len(results) >= lim {
			break
		}
	}
	return results, nil
}

// PopularPlanets is the resolver for the popularPlanets field.
func (r *queryResolver) PopularPlanets(ctx context.Context, limit *int) ([]*model.Planet, error) {
	if r.useMock() {
		lim := 5
		if limit != nil {
			lim = *limit
		}
		if lim > len(mockPlanets) {
			lim = len(mockPlanets)
		}
		return mockPlanets[:lim], nil
	}

	lim := int32(5)
	if limit != nil {
		lim = int32(*limit)
	}

	bodies, err := r.Repos.Body.Popular(ctx, lim)
	if err != nil {
		return nil, fmt.Errorf("popular planets: %w", err)
	}

	results := make([]*model.Planet, len(bodies))
	for i, b := range bodies {
		results[i] = repository.BodyToGraphQLPlanet(&b)
	}
	return results, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*model.Tag, error) {
	if r.useMock() {
		return mockTags, nil
	}

	if r.Cache != nil {
		var cached []*model.Tag
		if r.Cache.Get(ctx, cache.PrefixTags, &cached) {
			return cached, nil
		}
	}

	tags, err := r.Repos.Tag.List(ctx)
	if err != nil {
		return nil, fmt.Errorf("list tags: %w", err)
	}

	results := make([]*model.Tag, len(tags))
	for i, t := range tags {
		results[i] = repository.TagToGraphQL(&t)
	}

	if r.Cache != nil {
		r.Cache.Set(ctx, cache.PrefixTags, results, cache.TTLTags)
	}

	return results, nil
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*model.SiteStats, error) {
	if r.useMock() {
		return &model.SiteStats{
			TotalPlanets: len(mockPlanets), TotalComments: len(mockComments),
			TotalGalaxies: len(mockGalaxies), TotalTags: len(mockTags),
			TotalViews: 2944, RunningDays: 180,
		}, nil
	}

	if r.Cache != nil {
		var cached model.SiteStats
		if r.Cache.Get(ctx, cache.PrefixStats, &cached) {
			return &cached, nil
		}
	}

	planetCount, _ := r.Repos.Body.CountPublished(ctx)
	commentCount, _ := r.Repos.Comment.CountAll(ctx)
	galaxies, _ := r.Repos.Galaxy.ListGalaxies(ctx)
	tagCount, _ := r.Repos.Tag.Count(ctx)
	totalViews, _ := r.Repos.Body.SumViews(ctx)

	result := &model.SiteStats{
		TotalPlanets:  int(planetCount),
		TotalComments: int(commentCount),
		TotalGalaxies: len(galaxies),
		TotalTags:     int(tagCount),
		TotalViews:    int(totalViews),
		RunningDays:   int(time.Since(time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)).Hours() / 24),
	}

	if r.Cache != nil {
		r.Cache.Set(ctx, cache.PrefixStats, result, cache.TTLStats)
	}

	return result, nil
}

// FeedURL is the resolver for the feedUrl field.
func (r *queryResolver) FeedURL(ctx context.Context) (string, error) {
	return "/feed.xml", nil
}

// FriendLinks is the resolver for the friendLinks field.
func (r *queryResolver) FriendLinks(ctx context.Context) ([]*model.FriendLink, error) {
	if r.useMock() {
		return mockFriendLinks, nil
	}

	if r.Cache != nil {
		var cached []*model.FriendLink
		if r.Cache.Get(ctx, cache.PrefixFriends, &cached) {
			return cached, nil
		}
	}

	links, err := r.Repos.FriendLink.ListActive(ctx)
	if err != nil {
		return nil, fmt.Errorf("list friend links: %w", err)
	}

	results := make([]*model.FriendLink, len(links))
	for i, fl := range links {
		results[i] = repository.FriendLinkToGraphQL(&fl)
	}

	if r.Cache != nil {
		r.Cache.Set(ctx, cache.PrefixFriends, results, cache.TTLFriends)
	}

	return results, nil
}

// SiteSettings is the resolver for the siteSettings field.
func (r *queryResolver) SiteSettings(ctx context.Context) ([]*model.SiteSetting, error) {
	if r.useMock() {
		return mockSiteSettings, nil
	}

	settings, err := r.Repos.Settings.List(ctx)
	if err != nil {
		return nil, fmt.Errorf("list settings: %w", err)
	}

	results := make([]*model.SiteSetting, len(settings))
	for i, s := range settings {
		results[i] = repository.SettingToGraphQL(&s)
	}
	return results, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, bodySlug string) (<-chan *model.Comment, error) {
	ch := make(chan *model.Comment, 1)
	go func() {
		<-ctx.Done()
		close(ch)
	}()
	return ch, nil
}

// ReactionAdded is the resolver for the reactionAdded field.
func (r *subscriptionResolver) ReactionAdded(ctx context.Context, targetID string) (<-chan *model.Reaction, error) {
	ch := make(chan *model.Reaction, 1)
	go func() {
		<-ctx.Done()
		close(ch)
	}()
	return ch, nil
}

// OnlineCount is the resolver for the onlineCount field.
func (r *subscriptionResolver) OnlineCount(ctx context.Context, bodySlug *string) (<-chan int, error) {
	ch := make(chan int, 1)
	go func() {
		<-ctx.Done()
		close(ch)
	}()
	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// ---------- Mock fallback helpers ----------

func mockCreatePlanet(input model.CreatePlanetInput) (*model.Planet, error) {
	now := model.DateTime{Time: time.Now()}
	return &model.Planet{
		ID: fmt.Sprintf("p-%d", time.Now().UnixNano()), Title: input.Title, Slug: input.Slug,
		Content: input.Content, Excerpt: input.Excerpt, PhysicsParams: mockPhysics(3.0, 8.0, int(time.Now().Unix())),
		AestheticsParams: mockAesthetics(), Tags: []*model.Tag{}, Comments: []*model.Comment{},
		RelatedPlanets: []*model.Planet{}, CreatedAt: now, UpdatedAt: now, ReadingTime: 5,
	}, nil
}

func mockUpdatePlanet(slug string, input model.UpdatePlanetInput) (*model.Planet, error) {
	for _, p := range mockPlanets {
		if p.Slug == slug {
			if input.Title != nil {
				p.Title = *input.Title
			}
			return p, nil
		}
	}
	return nil, fmt.Errorf("planet not found: %s", slug)
}

func mockPublishPlanet(slug string) (*model.Planet, error) {
	for _, p := range mockPlanets {
		if p.Slug == slug {
			now := model.DateTime{Time: time.Now()}
			p.PublishedAt = &now
			return p, nil
		}
	}
	return nil, fmt.Errorf("planet not found: %s", slug)
}

func mockCreateComment(input model.CreateCommentInput) (*model.Comment, error) {
	return &model.Comment{
		ID: fmt.Sprintf("c-%d", time.Now().UnixNano()), BodySlug: input.BodySlug,
		AuthorName: input.AuthorName, AuthorEmail: &input.AuthorEmail,
		AvatarSeed: fmt.Sprintf("seed-%s", input.AuthorName),
		ContentHTML: "<p>" + html.EscapeString(input.Content) + "</p>",
		OrbitalParams: mockOrbital(0), ParentID: input.ParentID,
		Replies: []*model.Comment{}, Reactions: []*model.Reaction{},
		CreatedAt: model.DateTime{Time: time.Now()},
	}, nil
}

func mockPinComment(id string, pinned bool) (*model.Comment, error) {
	for _, c := range mockComments {
		if c.ID == id {
			c.Pinned = pinned
			return c, nil
		}
	}
	return nil, fmt.Errorf("comment not found: %s", id)
}

func mockLogin(cfg *config.Config, email, password string) (*model.AuthPayload, error) {
	if email != "admin@wo.city" || password != "password" {
		return nil, fmt.Errorf("invalid credentials")
	}
	secret := "change-me-in-production"
	expHrs := 24
	if cfg != nil {
		secret = cfg.Auth.JWTSecret
		expHrs = cfg.Auth.JWTExpireHrs
	}
	token, expiresAt, err := auth.GenerateToken(secret, mockUser.ID, mockUser.Email, string(mockUser.Role), expHrs)
	if err != nil {
		return nil, fmt.Errorf("generate token: %w", err)
	}
	return &model.AuthPayload{Token: token, ExpiresAt: model.DateTime{Time: expiresAt}, User: mockUser}, nil
}

func mockCreateGalaxy(input model.CreateGalaxyInput) (*model.Galaxy, error) {
	pos := &model.BaseCoordinates{X: 0, Y: 0, Z: 0}
	if input.Position != nil {
		pos = &model.BaseCoordinates{X: input.Position.X, Y: input.Position.Y, Z: input.Position.Z}
	}
	cs := &model.GalaxyColorScheme{Primary: "#38bdf8", Secondary: "#6b21a8"}
	if input.ColorScheme != nil {
		cs = &model.GalaxyColorScheme{Primary: input.ColorScheme.Primary, Secondary: input.ColorScheme.Secondary, Nebula: input.ColorScheme.Nebula}
	}
	return &model.Galaxy{
		ID: fmt.Sprintf("g-%d", time.Now().UnixNano()), Name: input.Name, Slug: input.Slug,
		Description: input.Description, Position: pos, ColorScheme: cs,
		Children: []*model.Galaxy{}, Bodies: []model.CelestialBody{},
		CreatedAt: model.DateTime{Time: time.Now()}, UpdatedAt: model.DateTime{Time: time.Now()},
	}, nil
}

func mockUpdateGalaxy(id string, input model.UpdateGalaxyInput) (*model.Galaxy, error) {
	for _, g := range mockGalaxies {
		if g.ID == id {
			if input.Name != nil {
				g.Name = *input.Name
			}
			return g, nil
		}
	}
	return nil, fmt.Errorf("galaxy not found: %s", id)
}

func mockCreateFriendLink(input model.CreateFriendLinkInput) (*model.FriendLink, error) {
	sortOrder := 0
	if input.SortOrder != nil {
		sortOrder = *input.SortOrder
	}
	return &model.FriendLink{
		ID: fmt.Sprintf("fl-%d", time.Now().UnixNano()), Name: input.Name, URL: input.URL,
		Description: input.Description, SortOrder: sortOrder, CreatedAt: model.DateTime{Time: time.Now()},
	}, nil
}

func mockUpdateFriendLink(id string, input model.UpdateFriendLinkInput) (*model.FriendLink, error) {
	for _, fl := range mockFriendLinks {
		if fl.ID == id {
			if input.Name != nil {
				fl.Name = *input.Name
			}
			return fl, nil
		}
	}
	return nil, fmt.Errorf("friend link not found: %s", id)
}

func mockSearchBodies() (*model.SearchResult, error) {
	var items []model.CelestialBody
	for _, p := range mockPlanets {
		items = append(items, p)
	}
	return &model.SearchResult{Items: items, Total: len(items), Page: 1, PageSize: 10}, nil
}

func mockArchiveByYear(year int) (*model.ArchiveResult, error) {
	months := make([]*model.ArchiveMonth, 0)
	for m := 1; m <= 12; m++ {
		var ps []*model.Planet
		for _, p := range mockPlanets {
			if p.PublishedAt != nil && p.PublishedAt.Year() == year && int(p.PublishedAt.Month()) == m {
				ps = append(ps, p)
			}
		}
		if len(ps) > 0 {
			months = append(months, &model.ArchiveMonth{Month: m, Planets: ps, Count: len(ps)})
		}
	}
	total := 0
	for _, mo := range months {
		total += mo.Count
	}
	return &model.ArchiveResult{Year: year, Months: months, Total: total}, nil
}

func mockCommentConnection(bodySlug string) (*model.CommentConnection, error) {
	var matching []*model.Comment
	for _, c := range mockComments {
		if c.BodySlug == bodySlug {
			matching = append(matching, c)
		}
	}
	edges := make([]*model.CommentEdge, 0, len(matching))
	for _, c := range matching {
		edges = append(edges, &model.CommentEdge{Cursor: c.ID, Node: c})
	}
	var sc, ec *string
	if len(edges) > 0 {
		sc = &edges[0].Cursor
		ec = &edges[len(edges)-1].Cursor
	}
	return &model.CommentConnection{
		Edges: edges, PageInfo: &model.PageInfo{StartCursor: sc, EndCursor: ec}, TotalCount: len(matching),
	}, nil
}

func mockRelatedPlanets(bodyID string, limit *int) ([]*model.RelationScore, error) {
	lim := 3
	if limit != nil {
		lim = *limit
	}
	var results []*model.RelationScore
	for i, p := range mockPlanets {
		if p.ID == bodyID {
			continue
		}
		results = append(results, &model.RelationScore{Planet: p, Score: 0.9 - float64(i)*0.1})
		if len(results) >= lim {
			break
		}
	}
	return results, nil
}
